name: Daily Update DB

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          # If you have a requirements.txt file, you can use:
          # pip install -r requirements.txt

      - name: Fetch custom node list
        run: python src/fetch_custom_node_list.py

      - name: Fetch GitHub stats
        run: python src/fetch_github_stats.py

      - name: Run script to merge, filter, and sort nodes
        run: |
          python src/merge_sort_and_filter_nodes.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add src/data/
          
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "update db"
            git push origin ${{ github.ref_name }}
          else
            echo "No changes to commit."
          fi
